### ISSUE TITLE
To-do for version 0.1

### ISSUE THREAD

**Issue by privet-kitty** [privet-kitty/Munsellpicker#1]
- [x] add JComboBox to choose RGB space
  - [x] enable to choose a space from sRGB and  AdobeRGB
  - [x] extend it to choose an arbitrary .dat file
  - [x] add error handling
- [x] write README.md
  - [x] screenshot
  - [x] summary
  - [x] available RGB spaces
  - [x] simple comment for conversion method
  - [x] about portability
  - [x] JRE 1.8 is the best
  - [x] link to the releases
- [x] write english comments on source
- [x] release .zip
